const types = {
    WRONG_EMAIL: 'WRONG_EMAIL',
    EXISTED_EMAIL: 'EXISTED_EMAIL',
    WRONG_USERNAME: 'WRONG_USERNAME',
    EXISTED_USERNAME: 'EXISTED_USERNAME',
    NOT_MATCHED_PASS: 'NOT_MATCHED_PASS',
    SUCCESS: 'SUCCESS',
    SUCCESS_FALSE: 'SUCCESS_FALSE',
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    UNSUCCESSFULL_LOG_IN: 'UNSUCCESSFULL_LOG_IN',
    RESET_STATE: 'RESET_STATE',
    POSTED: 'POSTED',
    RESET_POSTED: 'RESET_POSTED',
    SET_POSTS_CATEGORIES: 'SET_POSTS_CATEGORIES',
    SET_POSTS: 'SET_POSTS'
}

module.exports = types;